"""changed start and end type to Time

Revision ID: 2039777515e1
Revises: 47f2a394cd
Create Date: 2013-08-07 16:12:56.411686

"""

# revision identifiers, used by Alembic.
revision = '2039777515e1'
down_revision = '47f2a394cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
