"""changed start and end type to Time

Revision ID: 47f2a394cd
Revises: None
Create Date: 2013-08-07 15:52:51.089934

"""

# revision identifiers, used by Alembic.
revision = '47f2a394cd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
