"""changed start and end type to Time

Revision ID: 6dc0e69b27f
Revises: 2039777515e1
Create Date: 2013-08-07 16:18:03.168603

"""

# revision identifiers, used by Alembic.
revision = '6dc0e69b27f'
down_revision = '2039777515e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loads', u'start_time')
    op.drop_column('loads', u'end_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loads', sa.Column(u'end_time', sa.DATETIME(), nullable=True))
    op.add_column('loads', sa.Column(u'start_time', sa.DATETIME(), nullable=True))
    ### end Alembic commands ###
